#pragma once

enum MissionState : unsigned short {
	MISSION_AVAILABLE = 0, //0 or 1 (not sure)
	MISSION_ACTIVE,
	MISSION_READY_TO_COMPLETE,
	MISSION_COMPLETE,
	MISSION_FAIL,
	MISSION_READY_TO_COMPLETE_REPORTED
};